"""Initial migrations as

Revision ID: e92aa3a4264d
Revises: eb940804eb7c
Create Date: 2024-07-23 00:57:37.836685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e92aa3a4264d'
down_revision: Union[str, None] = 'eb940804eb7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gas_device_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('weight_reading', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gas_device_readings_id'), 'gas_device_readings', ['id'], unique=False)
    op.create_table('gas_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('battery_status', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gas_devices_device_id'), 'gas_devices', ['device_id'], unique=True)
    op.create_index(op.f('ix_gas_devices_id'), 'gas_devices', ['id'], unique=False)
    op.create_table('wall_adapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_count_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('connection_type', sa.String(), nullable=True),
    sa.Column('battery_status', sa.Float(), nullable=True),
    sa.Column('battery_health', sa.String(), nullable=True),
    sa.Column('power_source', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wall_adapters_device_id'), 'wall_adapters', ['device_id'], unique=False)
    op.create_index(op.f('ix_wall_adapters_id'), 'wall_adapters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wall_adapters_id'), table_name='wall_adapters')
    op.drop_index(op.f('ix_wall_adapters_device_id'), table_name='wall_adapters')
    op.drop_table('wall_adapters')
    op.drop_index(op.f('ix_gas_devices_id'), table_name='gas_devices')
    op.drop_index(op.f('ix_gas_devices_device_id'), table_name='gas_devices')
    op.drop_table('gas_devices')
    op.drop_index(op.f('ix_gas_device_readings_id'), table_name='gas_device_readings')
    op.drop_table('gas_device_readings')
    # ### end Alembic commands ###
